### ISSUE TITLE
Build broken with non-GNU make

### ISSUE THREAD

**Issue by melak** [freakout42/macrocalc#15]
```
$ git blame mc/Makefile.in
0cc5859c (Axel ... 393) binunits:     ../src/binunits.o
0cc5859c (Axel ... 394)       cp $< $@
```
This broke non-GNU make (namely FreeBSD (b)make). As far as I can tell, `$<` being the first prereq in GNU make is amended by _only if suffix rules are also at play_ with bmake. As there are no suffix rules here, `$<` evaulates to empty, and now the build is broken:
```
awk -F" " 'BEGIN {OFS=FS; print "Msgno", "Msgtext"; print "-----", "-------"; n = 0}  $2=="us" {print n++, $3}' <../src/mcmessag.rdb | sed 's/{NULL}//g' >mcmsg.rdb
awk -F" " '$2=="us" {print $3}' <../src/mcmenus.rdb  | tr ';' , >mcmnu.rdb
cp  binunits
usage: cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpsvx] source_file target_file
       cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpsvx] source_file ... target_directory
*** Error code 64

Stop.
```
Additionally, as all `Makefile`s call `make` and not `$(MAKE)` when doing recursion, it's also impossible to build with `gmake`, since the first recursion will revert back to using system (potentially not GNU) make.

**Comment by melak** [comment]
[This](https://forums.freebsd.org/threads/a-surprising-thing-about-bsd-make-suffix-rules.89767/) may or may not be interesting or relevant (I don't understand half of it).

**Comment by freakout42** [comment]
fixed with acc18003fddcb09546e26739d82cb4f42c42d60b - please try with main/trunc

**Comment by freakout42** [comment]
check with FreeBSD

**Comment by melak** [comment]
Brilliant, thank you very much!
