### ISSUE TITLE
`ident` used during build?

### ISSUE THREAD

**Issue by daveloyall** [freakout42/macrocalc#2]
Hello.

`mc/Makefile.in` references `ident`?  I have never heard of that command or binary.. Does it come from the rcs package?

I'm preparing a list of dependencies to install on Debian to build this but I'm not sure if I should include rcs or not.

**Comment by freakout42** [comment]
the debian dependencies are:
  sudo apt install libncurses-dev flex bison
the call of ident is not fatal for make and is optional
