### ISSUE TITLE
Precompiled binary needs libncurses.so.5 (current: libncurses.so.6)

### ISSUE THREAD

**Issue by Eucyon** [freakout42/macrocalc#7]
I am pleased to see that there is a "new" spreadsheet program for the cli for Linux. Thank you for sharing!

However, when I run the binary on an up-to-date Arch Linux, I get:
```
./mc
./mc: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```

I tried to link libncurses.so.5 to libncurses.so.6 in /usr/lib with no success. What's wrong?

**Comment by freakout42** [comment]
sorry - i currently dont have a linux with libncurses.so.6 - max is CentOS 7 which still is .5
on next release i will provide binary with .6
you have to go with the source-version
